### ISSUE TITLE
Use variablized `target_user` when creating user

### ISSUE THREAD

**Issue by Tjzabel** [jwflory/conf#7]
The default user created is `jflory`, however, this may not always be the case. It would be a good idea to use the `target_user` variable when creating the main user.  

https://github.com/jwflory/conf/blob/bd21d487e69d5cf1decdcc5deeb6b901f865d8a0/ansible/fedora/setup_fedora.yml#L150

**Comment by jwflory** [comment]
Closed via 6103dc781139f739be148014fccc54de548465a1. Verified and tested locally in Vagrant VM.
